### PR TITLE
Port OPE to Rust

### PR DESCRIPTION
**Pull request by avery-blanchard**
Order preserving encryption in rust based on the Boldyreva Order-Preserving Symmetric Encryption [paper](https://faculty.cc.gatech.edu/~aboldyre/papers/bclo.pdf) and a [python implementation](https://github.com/tonyo/pyope/blob/master/pyope/ope.py)

Still in progress 
1. Tape generation

### CODE REVIEW

**Comment by avery-blanchard** [comment]
Tape generation is complete. 
Updated To Do:
- Hypergeometric sampling 

Resources:
- https://github.com/tonyo/pyope/blob/master/pyope/stat.py#L5 
- https://github.com/tonyo/pyope/blob/aad20461ecf6ff3803b1007f1d2e6ec8839d7b69/pyope/hgd.py#L37
- Page 18 of the Boldyreva paper

**Comment by avery-blanchard** [comment]
Updated To Do
- Debug issues with the tape

**Comment by avery-blanchard** [comment]
Debugging, current issue:
- Sample returned in hyper-geometric algorithm is out of the input range.

**Comment by avery-blanchard** [comment]
Update: Some inputs work, and ordering is preserved!

New error: some inputs cause the hyper-geometric function to enter an infinite loop while sampling (samples until a sample is found that is acceptable to the distribution). 

Thoughts:
- As the input has no effect on the hyper-geometric  sampling (not a parameter), the issue is likely in tape generation (again).

**Comment by avery-blanchard** [comment]
Problems resolved!

**Comment by cyoon1729** [comment]
Amazing!!!

**Pull request merged**
